mixin:
  # Replace player login validation thread with virtual thread
  loginVT: true
  # Optimized VarLong implementation
  bestVarLong: true
  # Enable new encryption optimizations on the client side
  clientEncrypt: true
  # Optimized RconClient implementation
  rconClient: false
fix:
  issues128:
    # Fix Traffic Statistics
    enabled: false
    # Run bandwidth statistics on sync thread, which is closer to Vanilla behavior.
    sync: true
compress:
  # The compression level for packets, between 1-9.
  compressionLevel: 4
  # Permit Oversized Packets
  permitOversizedPackets: false
  blending-mode:
    # (Experimental) Delegate data packets with poor performance in the Native implementation to the Java implementation
    enabled: false
    linux-fallback-min-size: 1024
    repetitive-threshold: 0.6
netty:
  # Change Netty's default 16MiB memory allocation to 4MiB, as Minecraft has a 2MiB packet size limit.
  allocatorMaxOrder: 9