# Thirst Was Taken 配置 - Kaleidoscope Cookery 兼容
# 自动生成于: 2026-02-23T18:20:37.724612400

[Drinks]
# 饮用时恢复口渴的物品
drinks = []

[Foods]
# 食用时恢复口渴的物品
foods = [
    ["kaleidoscope_cookery:pork_bone_soup", 4, 6],
    ["kaleidoscope_cookery:seafood_miso_soup", 4, 6],
    ["kaleidoscope_cookery:fearsome_thick_soup", 4, 6],
    ["kaleidoscope_cookery:lamb_and_radish_soup", 4, 6],
    ["kaleidoscope_cookery:braised_beef_with_potatoes", 4, 6],
    ["kaleidoscope_cookery:wild_mushroom_rabbit_soup", 4, 6],
    ["kaleidoscope_cookery:tomato_beef_brisket_soup", 4, 6],
    ["kaleidoscope_cookery:pufferfish_soup", 4, 6],
    ["kaleidoscope_cookery:borscht", 4, 6],
    ["kaleidoscope_cookery:beef_meatball_soup", 4, 6],
    ["kaleidoscope_cookery:chicken_and_mushroom_stew", 4, 6]
]

[Blacklist]
# 禁用口渴支持的物品
itemsBlacklist = []
