[client]
	#Off the Custom Rendering
	shadersCompat = false
	#ScreenShake(on/off)
	"ScreenShake(on/off)" = true
	#Forced viewpoint change when hit by a grab attack
	"setThirdPerson(on/off)" = true
	#Forced viewpoint change when hit by a grab attack
	"setFirstPerson(on/off)" = true
	#custombossbar(on/off)
	"custombossbar(on/off)" = true
	#custombossbar(on/off)
	"BossMusic(on/off)" = true
	#BossMusicVolume
	# Default: 1
	# Range: 1 ~ 100
	BossMusicVolume = 1
