#k值为饥饿值转换为饱和度的比例
# Default: 0.5
# Range: 0.0 ~ 1.0
K = 0.5
#饱和度最大值
# Default: 20.0
# Range: 0.0 ~ 3.4028234663852886E38
MAX = 20.0
#十进制有符号颜色代码
# Default: -16777216
# Range: > -2147483648
RGB = -16777216
