# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
cosmeticScreenKeybind: true
globalTooltip: false
noMicrosoftTelemetry: true
qol:
  suppressExperimentalSettingsWarning: false
  titleScreenNoFade: false
  hideDataComponentsTooltip: false
  loadingOverlayNoFade: false
debug:
  showTranslatedTagsByDefault: false
  printDataComponentsWhenCopy: true
  tagsTooltip: true
  debugTooltipMsg: false
  tagsTooltipAppendKeybindHint: false
  F3CopyInInventory: true
  tagsPerPage: 6
