[general]
	#Whether to display disclaimer GUI
	DisclaimerShow = false
	#Whether to print animation roulette play message
	PrintAnimationRouletteMsg = false
	#Prevents rendering of self player's model
	DisableSelfModel = false
	#Prevents rendering of other player's model
	DisableOtherModel = false
	#Prevents rendering of self player's hand
	DisableSelfHands = false
	#Prevents rendering of projectile model
	DisableProjectileModel = false
	#Prevents rendering of vehicle model
	DisableVehicleModel = false
	#If rendering errors occur, try turning on this.
	UseCompatibilityRenderer = false
	#The amount of volume when the animation is played.
	# Default: 100.0
	# Range: 0.0 ~ 100.0
	SoundVolume = 100.0
	#Whether to display model ID first in the model selection screen, instead of the model name filled in by the model author.
	ShowModelIdFirst = false

[extra_player_render]
	#Whether to display player
	DisablePlayerRender = false
	#Player position x in screen
	# Default: 10
	# Range: > 0
	PlayerPosX = 10
	#Player position y in screen
	# Default: 10
	# Range: > 0
	PlayerPosY = 10
	#Player scale in screen
	# Default: 40.0
	# Range: 8.0 ~ 360.0
	PlayerScale = 40.0
	#Player yaw offset in screen
	# Default: 5.0
	# Range: 4.9E-324 ~ 1.7976931348623157E308
	PlayerYawOffset = 5.0

[loading_state_screen]
	#Whether to disable loading state screen
	DisableLoadingStateScreen = false
	#Loading state screen position
	#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	LoadingStatePosition = "BOTTOM_RIGHT"
